# Generated by Django 4.0.6 on 2023-02-28 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhulkeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
