# Generated by Django 4.0.6 on 2023-03-01 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BhulkeeApp', '0006_alter_messages_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillists',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='heading',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
