# Generated by Django 4.0.6 on 2023-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhulkeeApp', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='heading',
            field=models.CharField(max_length=500),
        ),
    ]
