# Generated by Django 4.0.6 on 2023-03-01 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BhulkeeApp', '0009_alter_messages_body_alter_messages_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillists',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
