# Generated by Django 4.0.6 on 2023-03-01 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BhulkeeApp', '0010_alter_maillists_id_alter_messages_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillists',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
